### ISSUE TITLE
[BUG]Not inicialized Admob

### ISSUE THREAD

**Issue by miqueias9889** [Poing-Studios/godot-admob-android#103]
Vi que você é brasileiro vou escrever em portugues mesmo

Aqui eu to tentando fazer seu plugin funcionar aqui, mas não to conseguindo, é que meu pc é 32 bits ai eu gero o AAB para android manualmente sem gradle o sabe, eu baixei todas as dependencias necessarias e uso javac e d8 aapt2 32bits que achei nos repositorios debian para conseguir isso, mas ai não sei o que falta, você que fez o plugin poderia me ajudar, porque por exemplo para conseguir gerar o aab e apk por cmdline eu primeiro gero um apk no godot com plugins desmarcados para depois dar unzip neste apk e pegar a pasta assets o resto é compilar .java em .class e converter .class em .dex e etc também passo o seu lib aar para o d8, mas bem o que queria saber é se quando aquela opção de ativar desativar o plugin quando vai exportar para android muda alguma coisa no projeto para o plugin funcionar além de mandar o gradle compilar o seu admob-release.aar e baixar a dependencia ads que é necessária?

O que queria entender é como funciona um plugin no godot, como o godot chama seu plugin para ele funcionar? e se esta parte como disse de marca o plugin na hora de exportar muda mais alguma coisa além de definir para compilar a sua lib aar?

Se possivel você poderia compartilhar comigo um apk com seu plugin funcionando para mim ver se falta alguma dependencia que não botei?

Obrigado!!!

**Comment by miqueias9889** [comment]
Obrigado, mas deixa pra lá conseguir fazer funcionar, falta algumas coisas no AndroidManifest.xml

**Comment by gumaciel** [comment]
Olá, obrigado por usar nosso plugin e desculpe pela demora.

Que bom que você conseguiu resolver alterando no `AndroidManifest.xml`, respondendo sua pergunta sobre como o plugin funciona/se comunica com a Godot, talvez esse link da nossa wiki lhe ajude: https://github.com/Poing-Studios/godot-admob-android/wiki/Android-Plugin#developing

Já que você resolveu o seu problema eu vou fechar essa Issue, mas você pode reabrir quando quiser, obrigado!

---
Hi, thank you for using our plugin and sorry for the delay.

Glad you were able to solve it by changing the `AndroidManifest.xml`, answering your question about how the plugin works/communicates with Godot, maybe this link on our wiki will help you: https://github.com/Poing-Studios/godot-admob-android/wiki/Android-Plugin#developing

Since you solved your problem I will close this issue, but you can reopen it whenever you want, thanks!
