### ISSUE TITLE
[BUG] Banner Ad overlaps with Notch area.

### ISSUE THREAD

**Issue by ebudagov** [Poing-Studios/godot-admob-android#115]
**Describe the bug**
Hi,
Banner Ad overlaps notch area when banner placement is set to Top
I reproduced this on Galaxy A70, with Banner type of Smart, and Adaptive

**To Reproduce**
1. Enable Banner
2. Set Banner Size to ADAPTIVE
3. Enable Banner on Top checkbox
4. Launch App and see some Banner information is hidden behind Notch area

**Expected behavior**
Not sure if this is expected or not. On Iphone, banner is shown within safe area. Issue only reproducable on Android
![E641E95C-C4B0-499D-9ACF-1E3FC53C9EB3 3](https://user-images.githubusercontent.com/56162893/170828865-a9fb32d7-8fb3-46a2-a5e2-7dbd114a0548.JPG)

**Screenshots**
Screenshot attached

**Smartphone (please complete the following information):**
 - Device: [Samsung Galaxy A70]
 - OS: [Android]
 - Version [11]

**Comment by gumaciel** [comment]
Thank you for openning this issue, i will try to this it as soon as possible


`Not sure if this is expected or not.`
I believe the ad should be within the safe area for both Android and iOS, so we need to fix:

iOS:
https://developers.google.com/admob/ios/x-ad-rendering

![image](https://user-images.githubusercontent.com/20030153/170847094-fd7586a1-e129-4103-831b-32f6560f302e.png)

For Android we don't have this kind of documentation by Google, but i believe the correct is to be the same as iPhone.

**Comment by gumaciel** [comment]
@ebudagov A new version was Released in order to fix this bug, please test it:

https://github.com/Poing-Studios/godot-admob-editor/releases/tag/v1.3.0
https://github.com/Poing-Studios/godot-admob-android/releases/tag/v2.1.0

Note: https://github.com/Poing-Studios/godot-admob-editor/issues/28 a `RepectSafeArea` option on Banner Tab was added, the default value is `true` (as expected) but the programmer can choice to `false` if he wants to.

**Comment by shovel-games** [comment]
Hello,

The latest version of AdMob (v3.1.2) appears to have this issue again. The following was taken on Samsung Galaxy A32 (2020)

![Image](https://github.com/user-attachments/assets/84f631f0-e827-4797-8f77-9f6fee719d87)
