### ISSUE TITLE
 Unable to load banner at the bottom.

### ISSUE THREAD

**Issue by DerSchlaueFrosch** [Poing-Studios/godot-admob-android#172]
### Godot version

4.0.3

### Plugin version

v2.1.4

### Phone information

android 13

### Issue description

The banner loads correctly, but if you deselect 'Banner on Top' in the editor or 'Position checked TOP' in the Example.tscn, it fails to load altogether.

### Steps to reproduce

1. Run Example.tscn on your phone.
2. Navigate to the Banner tab.
3. Uncheck 'Position checked TOP'.
4. Go to the AdFormats tab.
5. Click on "Enable Banner."

**Comment by gumaciel** [comment]
Hi, sorry about this, we will investigate it

**Comment by djrain** [comment]
Perhaps because of this:
<img width="979" alt="Screenshot 2023-06-06 at 4 38 42 PM" src="https://github.com/Poing-Studios/godot-admob-android/assets/33777501/14487fd4-3a2b-4438-90ba-15c6bf1f0a58">

But, weirdly, I'm having trouble loading banners with any settings, even after fixing that. All the other ad types are working.
