### ISSUE TITLE
Game restarts when opens an ad, goes to "home" and back to app

### ISSUE THREAD

**Issue by gumaciel** [Poing-Studios/godot-admob-android#187]
### Discussed in https://github.com/Poing-Studios/godot-admob-android/discussions/186

<div type='discussions-op-text'>

<sup>Originally posted by **orah29** September  6, 2023</sup>
With the sample project supplied with the plugin, after clicking on ads (banner or interstitial) :
if I press on home/overview button, the app closes;
if I press on back button, I return on ads. Then I close the ads to return to the app.
How to fix this?
Thanks in avance</div>

**Comment by gumaciel** [comment]
@orah29 Just tested on v2.0.0 on Godot 4.1.1 and v1.0.0 on Godot 3.5.2:

On Godot 3.5.2 it doesn't happen, but on Godot 4.1.1 it happens.

The code of v2 and v1 is kind of the same, plus we are just calling available AdMob methods, which shouldn't cause this bug.

Everything indicates that the bug is something related to the rendering of Godot 4, I recommend that you open an issue in the Godot repository to track this problem.

**Comment by orah29** [comment]
Same issue with Godot 4.1.1 and  Admob v3.0.0
I try a simple godot project that open YouTube and Web browser : no issue.

**Comment by gumaciel** [comment]
Version v2.0.0, which is quite simple, causes this bug, so I believe it is some functionality in Google's own AdMob SDK that causes this problem on Android for Godot 4.

If possible, try to create a simple Android AdMob plugin with the functionality you need and check if the same bug occurs.

But I believe the same thing will happen, as I would say that v2 is simple enough

**Comment by orah29** [comment]
Thanks for your answer. Unfortunately I do not have the competence to develop a plugin myself. So I'll wait for a future version of Godot to solve the problem !  Envoyé à partir de Courrier pour Windows De : Gustavo MacielEnvoyé le :dimanche 10 septembre 2023 21:37À : Poing-Studios/godot-admob-androidCc : orah29; MentionObjet :Re: [Poing-Studios/godot-admob-android] Game restarts when opens an ad, goes to "home" and back to app (Issue #187) Version v2.0.0, which is quite simple, causes this bug, so I believe it is some functionality in Google's own AdMob SDK that causes this problem on Android for Godot 4.If possible, try to create a simple Android AdMob plugin with the functionality you need and check if the same bug occurs.But I believe the same thing will happen, as I would say that v2 is simple enough—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
